import "./globals.css";
import type { Metadata } from "next";
import { Header } from "@/components";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const styles = {
  body: "w-full h-screen flex flex-col justify-start items-center",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " " + styles.body}>
        <Header />

        {children}
      </body>
    </html>
  );
}
